config/routes.rb
Rails.application.routes.draw do
	scope '(:locale)' do
		resources :categories
		resources :users
		resources :orders
		resources :line_items
		resources :carts
		resources :products

		get '/store/index'
		post '/store/index'
		post '/store/category' => 'store#category'

		get '/admin' => 'admin#index'
		get '/about' => 'store#about'
		get '/contact' => 'store#contact'

		get 'login' => 'sessions#new'
		post 'login' => 'sessions#create'
		delete 'logout' => 'sessions#destroy'

		root 'store#index'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :authorize
	before_action :set_i18n_locale_from_params
	helper_method :current_user

	protected
   def authorize
		 unless User.find_by_id(session[:user_id])
			 redirect_to login_url, notice: "Please Log in"
		 end
   end

	 def set_i18n_locale_from_params
		 if params[:locale]
			 if I18n.available_locales.include?(params[:locale].to_sym)
				 I18n.locale = params[:locale].to_sym
			 else
				 flash[:notice] = "#{params[:locale]} translation not available"
				 logger.error flash[:notice]
			 end
		 end
	 end

	 def default_url_options
		 { locale: I18n.locale }
	 end

	 def current_user
		 User.find(session[:user_id])
	 rescue ActiveRecord::RecordNotFound
		 nil
	 end

	private
	 def current_cart
		 Cart.find(session[:cart_id])
	 rescue ActiveRecord::RecordNotFound
		 cart = Cart.create
		 session[:cart_id] = cart.id
		 cart
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_form_for(object, options = {}, &block)
		options[:builder] = BootstrapFormBuilder
		form_for(object, options, &block)
	end
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Pragmatic Store</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse navbar_link_list">
			<ul class="nav navbar-nav">
				<li class="navbar-link"><a href="/"><%= t('application.home')%></a></li>
				<li class="navbar-link"><a href="/about"><%= t('application.about')%></a></li>
				<li class="navbar-link"><a href="/contact"><%= t('application.contact')%></a></li>
			</ul>
		</div>
		<div class="collapse navbar-collapse">
			<div class="navbar-user_info navbar-right">
				<% if session[:user_id].nil? %>
					<%= link_to 'Login', login_path, class: "navbar-login btn btn-primary" %>
				<% else %>
					<div class="btn-group">
					  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<%= current_user.name %> <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu">
							<li>
								<%= link_to 'Logout', logout_path, method: :delete %>
								<%= link_to 'Control Panel', admin_path %>
							</li>
					  </ul>
					</div>
				<% end %>
			</div>

			<%= form_tag store_index_path, class: "locale" do %>
				<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), class: " form-control", onchange: 'this.form.submit()' %>
			<% end %>
		</div>
	</div>
</nav>